version: '3.5'
services:    
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ${LDAP_SERVER}
    ports:
#      - "1080:80"
      - "1443:443"
    networks:
#      - ldapStagingNetwork
      - ldapNetwork
networks:
  ldapNetwork:
    external: true
#  ldapProductNetwork:
#    external: true
