version: '3.5'
services:
  pwm:
    image: 120896031351.dkr.ecr.ap-northeast-2.amazonaws.com/pwm/pwm-webapp:latest
    container_name: pwm
    ports:
      - "4443:8443"
#      - "2080:8080"
    volumes:
      - config:/config
    networks:
#      - ldapStagingNetwork
      - ldapNetwork
volumes:
  config:
networks:
  ldapNetwork:
    external: true
