version: '3.5'
services:    
  jenkins:
    container_name: jenkins
    # https://github.com/openfrontier/docker-jenkins
    image: jenkins/jenkins:lts
    volumes:
      - jenkins_home:/var/jenkins_home
    user: root
    environment:
      JENKINS_OPTS: "--httpPort=-1 --httpsPort=8443"
    ports:
      - 3443:8443
    networks:
      - ldapNetwork
volumes:
  jenkins_home:
networks:
  ldapNetwork:
    external: true
